### ISSUE TITLE
求助：讲台上的计算机经常断网

### ISSUE THREAD

**Issue by heroxbd** [physics-data/faq#3]
1. 试着看了网络配置，断网时 IP 地址还在
2. 断网时无法访问  auth4.tsinghua.edu.cn
3. 一般来说，五分钟之内会恢复

请问我应该排查其它什么地方？

**Comment by Harry-Chen** [comment]
1. 多喝热水
2. 重启试试
3. 拨打 62784859 反映问题

**Comment by jiegec** [comment]
1. Do not GuGuGu
